name: Benchmark D Compiler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up D environment
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y hyperfine jq time

      - name: Create Hello World File
        run: |
          echo 'import std.stdio; void main() { writeln("Hello, World!"); }' > hello.d

      - name: Compile and Benchmark
        run: |
          echo "Compiling hello.d..."
          dmd hello.d -of=hello

          echo "Benchmarking execution time..."
          hyperfine --warmup 1 "./hello"

          echo "Measuring memory usage..."
          /usr/bin/time -v ./hello || true
