name: Benchmark D Compiler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up D environment
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y hyperfine jq time git

      - name: Create benchmark output
        run: |
          echo 'import std.stdio; void main() { writeln("Hello, benchmark!"); }' > hello.d
          dmd hello.d -of=hello
          /usr/bin/time -v ./hello 2>&1 | tee time_output.txt
          hyperfine --warmup 1 "./hello" --export-json benchmark_result.json

      - name: Save benchmark results to benchmark-history branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "benchmark-bot"
          git config --global user.email "benchmark-bot@users.noreply.github.com"
          git clone --branch benchmark-history https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} history-folder
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          mkdir -p history-folder/results/$TIMESTAMP
          cp benchmark_result.json time_output.txt history-folder/results/$TIMESTAMP/
          cd history-folder
          git add .
          git commit -m "Add benchmark results - $TIMESTAMP"
          git push origin benchmark-history
